# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_reco.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser_reco.proto\"U\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x61rticle_num\x18\x03 \x01(\x05\x12\x12\n\ntime_stamp\x18\x04 \x01(\x03\"/\n\x07\x41rticle\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\x12\x13\n\x0b\x61rticle_num\x18\x02 \x01(\x05\"E\n\x06param2\x12\r\n\x05\x63lick\x18\x01 \x01(\t\x12\x0f\n\x07\x63ollect\x18\x02 \x01(\t\x12\r\n\x05share\x18\x03 \x01(\t\x12\x0c\n\x04read\x18\x04 \x01(\t\"2\n\x06param1\x12\x0f\n\x07post_id\x18\x01 \x01(\x03\x12\x17\n\x06params\x18\x02 \x01(\x0b\x32\x07.param2\"J\n\x05Track\x12\x10\n\x08\x65xposure\x18\x01 \x01(\t\x12\x1b\n\nrecommends\x18\x02 \x03(\x0b\x32\x07.param1\x12\x12\n\ntime_stamp\x18\x03 \x01(\x03\"\x1a\n\x07Similar\x12\x0f\n\x07post_id\x18\x01 \x03(\x03\x32]\n\rUserRecommend\x12!\n\x0euser_recommend\x12\x05.User\x1a\x06.Track\"\x00\x12)\n\x11\x61rticle_recommend\x12\x08.Article\x1a\x08.Similar\"\x00\x62\x06proto3')



_USER = DESCRIPTOR.message_types_by_name['User']
_ARTICLE = DESCRIPTOR.message_types_by_name['Article']
_PARAM2 = DESCRIPTOR.message_types_by_name['param2']
_PARAM1 = DESCRIPTOR.message_types_by_name['param1']
_TRACK = DESCRIPTOR.message_types_by_name['Track']
_SIMILAR = DESCRIPTOR.message_types_by_name['Similar']
User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_reco_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

Article = _reflection.GeneratedProtocolMessageType('Article', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLE,
  '__module__' : 'user_reco_pb2'
  # @@protoc_insertion_point(class_scope:Article)
  })
_sym_db.RegisterMessage(Article)

param2 = _reflection.GeneratedProtocolMessageType('param2', (_message.Message,), {
  'DESCRIPTOR' : _PARAM2,
  '__module__' : 'user_reco_pb2'
  # @@protoc_insertion_point(class_scope:param2)
  })
_sym_db.RegisterMessage(param2)

param1 = _reflection.GeneratedProtocolMessageType('param1', (_message.Message,), {
  'DESCRIPTOR' : _PARAM1,
  '__module__' : 'user_reco_pb2'
  # @@protoc_insertion_point(class_scope:param1)
  })
_sym_db.RegisterMessage(param1)

Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), {
  'DESCRIPTOR' : _TRACK,
  '__module__' : 'user_reco_pb2'
  # @@protoc_insertion_point(class_scope:Track)
  })
_sym_db.RegisterMessage(Track)

Similar = _reflection.GeneratedProtocolMessageType('Similar', (_message.Message,), {
  'DESCRIPTOR' : _SIMILAR,
  '__module__' : 'user_reco_pb2'
  # @@protoc_insertion_point(class_scope:Similar)
  })
_sym_db.RegisterMessage(Similar)

_USERRECOMMEND = DESCRIPTOR.services_by_name['UserRecommend']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=19
  _USER._serialized_end=104
  _ARTICLE._serialized_start=106
  _ARTICLE._serialized_end=153
  _PARAM2._serialized_start=155
  _PARAM2._serialized_end=224
  _PARAM1._serialized_start=226
  _PARAM1._serialized_end=276
  _TRACK._serialized_start=278
  _TRACK._serialized_end=352
  _SIMILAR._serialized_start=354
  _SIMILAR._serialized_end=380
  _USERRECOMMEND._serialized_start=382
  _USERRECOMMEND._serialized_end=475
# @@protoc_insertion_point(module_scope)
